### ISSUE TITLE
escape column names in tests

### ISSUE THREAD

**Issue by hz-lschick** [dbt-msft/dbt-sqlserver#121]
The test sql scripts do not escape spaces in column names. It is required to do this by myown in the schema definition.

### Sample:

    
```yml
version: 2

models:
    - name: my_model
      columns:
          - name: "[Account Type]"
            tests:
                - not_null
```
works but
```yml
version: 2

models:
    - name: my_model
      columns:
          - name: Account Type
            tests:
                - not_null
```
fails
