### ISSUE TITLE
snapshot uses "limit"

### ISSUE THREAD

**Issue by ElectricLlama** [dbt-msft/dbt-sqlserver#123]
I'm using dbt 0.18.1, dbt-sqlserver 0.18.0, SQL Server 2019 developer edition. database compatibility level 150

I'm creating a snapshot model like so (using AdventureWorks):

```
{% snapshot person_snapshot %}

{{ config(
    target_database='AdventureWorks2017',
    target_schema='dbt',
    unique_key='BusinessEntityId',
    strategy='check',
    check_cols='all',
    tags=["dimension","HR"]
    ) }}

SELECT *
  FROM {{ source('MySources','Person')}} P

{% endsnapshot %}
```

I get this error:

>Database Error in snapshot person_snapshot (snapshots\PersonSnapshot.SQL)
 > ('42000', "[42000] [Microsoft][SQL Server Native Client 11.0][SQL Server]An expression of non-boolean type specified in a >context where a condition is expected, near 'limit'. (4145) (SQLExecDirectW)")

When I look in the log, it's running this:

```
select * from (
SELECT *
  FROM "AdventureWorks2017"."Person"."Person" P
        ) as __dbt_sbq
        where false
        limit 0
```

My profiles.yml looks like this:

```
default:
  target: dev
  outputs:
    dev:
      type: sqlserver
      driver: 'SQL Server Native Client 11.0'
      server: 127.0.0.1
      port: 1433
      database: AdventureWorks2017
      schema: dbt
      threads: 4
      user: abc
      password: xyz
      #windows_login: True

# https://github.com/fishtown-analytics/dbt/issues/399
# This stops "tracking disabled" message coming up
config:
    send_anonymous_usage_stats: False
```

Obviously limit is not valid T-SQL

Is this something that can be fixed in this plugin or does it need to be fixed on the dbt side?

As I work further through this my advice is: don't use AdventureWorks to experiment as it is a showcase for a whole bunch of SQL specific features (XML schemas, user defined types) that aren't supported by this plugin.I dont think the features are actually useful enough to bother trying to support anyway though.
