### ISSUE TITLE
connecting to sql server on docker container with driver issues

### ISSUE THREAD

**Issue by annajb** [dbt-msft/dbt-sqlserver#180]
I apologize ahead of time for probably describing this terribly, but I'm not sure if what I want to do is even possible.

I wanted to setup a local playground for learning dbt. I didn't want to pay for a cloud warehouse service, so I thought one of my better options would be to setup SQL Server in a docker container (MacOS) and then just setup my dbt profile to link to it. I felt like this would be such a fun local way of learning dbt without paying money for another service. I got Docker and SQL Server running properly per [this page](https://database.guide/how-to-install-sql-server-on-a-mac/), and I even was able to connect to it using both command line and the good ol' DBeaver gui. Seemed like I was on the right track and everything was dandy. 

My dbt profile was setup as follows:

```
dbt-mssql-dev:
  target: dev
  outputs:
    dev:
      type: sqlserver
      server: localhost
      driver: 'ODBC Driver 17 for SQL Server'
      port: 1433
      database: dbt
      schema: dev
      authentication: ActiveDirectoryPassword
      user: sa
      password: '<password>'
```

But then when I go and run `dbt debug`, I get the following response:

```
The database returned the following error:

  >Database Error
  ('08001', '[08001] [Microsoft][ODBC Driver 17 for SQL Server]Client unable to establish connection (0) (SQLDriverConnect)')
```

My gut is telling me I don't have my driver set up properly, but that's where my brain breaks and I feel like I don't know what to do. I've tried reinstalling the driver, but nothing. 

I'm hoping someone will be able to tell me... "silly goose, you don't have the driver configured properly" or a simple "nope nope nope, this won't work." 

Any guidance or help will be much much much much much much appreciated.
