### ISSUE TITLE
Define as_columnstore=false from dbt_project.yml

### ISSUE THREAD

**Issue by KimchaC** [dbt-msft/dbt-sqlserver#21]
Hi,

I am trying to define the config option `as_columnstore` from `dbt_project.yml`:
```yml
models:
  my_project:
    mart:
      materialized: table
      as_columnstore: False
```

The `materialized` config works, but `as_columnstore` seems to be ignored.

Am I doing something wrong or is this currently unsupported?

Thanks, Kim

**Comment by mikaelene** [comment]
I am not sure if it is supported in dbt_project.yml? Does it work for you in a model file?

**Comment by swanderz** [comment]
@KimchaC this works for us! are you still having this issue?
```
models:
  finance_data:
    +as_columnstore: False
```

**Comment by swanderz** [comment]
@KimchaC please reply back if you still can't get it working! we'd love to help out.

**Comment by infused-kim** [comment]
Sorry for the late reply, I completely forgot about this issue and ended up disabling columnstore indexes on each model at the time.

But I just tested it and it's working.

In addition to that, people who are using DBs without columnstore indexes, should also disable columnstore indexes on tests:
```yml
tests:
  my_project_name:
    +as_columnstore: False
```
