### ISSUE TITLE
Segmentation fault when using CLI auth

### ISSUE THREAD

**Issue by AkhilGNair** [dbt-msft/dbt-sqlserver#280]
In a clean venv I have run `pip install dbt-sqlserver`.

When running `dbt debug` with a basic `profiles.yml`, 

```
default:
  target: dev
  outputs:
    dev:
      type: sqlserver
      driver: "ODBC Driver 18 for SQL Server"
      server: server.database.windows.net
      database: ...
      schema: dbo
      port: 1433
      authentication: auto
```

I was hitting the following error

```
> dbt debug
16:26:02  Running with dbt=1.1.2
dbt version: 1.1.2
python version: 3.10.5
python path: ...
os info: Linux-5.15.0-46-generic-x86_64-with-glibc2.31
Using profiles.yml file at ...
Using dbt_project.yml file at ...

Configuration:
  profiles.yml file [OK found and valid]
  dbt_project.yml file [OK found and valid]

Required dependencies:
 - git [OK found]

Connection:
  server: ...
  database: ...
  schema: ...
  port: 1433
  UID: None
  client_id: None
  authentication: auto
  encrypt: False
  trust_cert: False
Segmentation fault (core dumped)
~/.pyenv/versions/3.10.5/lib/python3.10/multiprocessing/resource_tracker.py:224: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
```

This was pretty tricky to debug. Eventually I found an issue pointing to a problem in `pyodbc`: https://github.com/mkleehammer/pyodbc/issues/1081

Turns out all my problems went away after using this line to install `dbt-sqlserver` instead

```
pip install dbt-sqlserver --no-binary=pyodbc
```

So nothing to do on this issue :) . This just took me a while to debug, and maybe it will help someone else.
