### ISSUE TITLE
Mac only - Passwords with "#" character are not parsed correctly by dbt

### ISSUE THREAD

**Issue by matsonj** [dbt-msft/dbt-sqlserver#324]
```
% dbt --version         
Core:
  - installed: 1.3.2
  - latest:    1.3.2 - Up to date!

Plugins:
  - sqlserver: 1.3.0 - Up to date!
```

How to repro:

1. Create a new user in SSMS (or your tool of choice) and put a "#" in the password
2. Attempt to login with the versions above from a Mac.
3. You will see below:
![image](https://user-images.githubusercontent.com/16811433/213057153-73e18159-693c-43d6-98b2-8ca969e5adfd.png)
4. set a new password without the pound sign.
5. You will now be able to login

**Comment by mikaelene** [comment]
yml sees # as a special character. Probably needs to escaped (or enclosed with ""?)

Can this be a clue?

https://yaml.org/spec/1.2.2/#53-indicator-characters

**Comment by sdebruyn** [comment]
@matsonj Did you try the suggestion which @mikaelene suggested? You could also put it in an environment variable and reference it that way.

**Comment by matsonj** [comment]
@sdebruyn Yes that wrapper would work. We have a fix for this, but weird that it is broken on mac and fine on windows?

**Comment by sdebruyn** [comment]
Do you have the YAML for us? Do you experience the same when you use a `#` in a description of a column (making it appear / not appear in your dbt docs)?

**Comment by sdebruyn** [comment]
This profile works without issues on my Mac:

```
config:
  send_anonymous_usage_stats: false
test:
  outputs:
    default:
      database: msdb
      driver: ODBC Driver 18 for SQL Server
      encrypt: true
      host: 127.0.0.1
      pass: Secret#Secret
      port: 1433
      retries: 2
      schema: test16843923917434720607_test_basic
      trust_cert: true
      type: sqlserver
      user: IHaveAHashtag
  target: default
```

Anything I missed?
