### ISSUE TITLE
can not log into sql server using domain account

### ISSUE THREAD

**Issue by yxl1108** [dbt-msft/dbt-sqlserver#430]
OS: WSL2 / Ubuntu 20.04.6 LTS (Focal Fossa)
Driver: Microsoft ODBC Driver 18 for SQL Server

Installation: 
curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -
curl https://packages.microsoft.com/config/debian/11/prod.list > /etc/apt/sources.list.d/mssql-release.list
apt-get update
ACCEPT_EULA=Y apt-get install -y msodbcsql18
apt-get install -y unixodbc-dev gnupg libkrb5-dev pkg-config

dbt profile.yml:
local:
    type: sqlserver
    driver: 'ODBC Driver 18 for SQL Server'
    server: sql-server-instance.domain.com
    port: 1433
    trust_cert: true
    database: database_name
    schema: dbo
    authentication: ActiveDirectoryPassword
    user: 'DOMAIN\username'
    password: 'password'
    threads: 4

Error:
with authentication: ActiveDirectoryPassword

Database Error
  ('28000', "[28000] [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]Login failed for user ''. (18456) (SQLDriverConnect)")

without authentication: ActiveDirectoryPassword

Database Error
  ('28000', "[28000] [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]Login failed for user 'DOMAIN\\username'. (18456) (SQLDriverConnect)")

Observations:
sql server authentication works fine

**Comment by NicolasPA** [comment]
If it can help, this is what we're using to connect with the Windows user of the current session.
```yaml
dbt-transform:
  target: local
  outputs:
    local:
      type: sqlserver
      driver: 'ODBC Driver 17 for SQL Server'
      server: my_server\name
      port: 1433
      trusted_connection: True
      encrypt: False
      threads: 2
      database: my_db
      schema: my_local_schema
```
