### ISSUE TITLE
Port is not being applied properly when using Windows Login

### ISSUE THREAD

**Issue by cody-scott** [dbt-msft/dbt-sqlserver#496]
When calling `dbt debug` from windows using the following profile, the windows login defaults to the Fabric adapter implementation, which omits the port from the connection string.

```yml
dbt_project:
  target: dev
  outputs:
    dev:
      type: sqlserver
      driver: 'ODBC Driver 18 for SQL Server'
      server: 0.0.0.0
      port: 1444
      database: data_base
      schema: dbt
      trust_cert: true
      encrypt: false
      windows_login: true
```

this resolves to

`DRIVER={ODBC Driver 18 for SQL Server};SERVER=0.0.0.0;Database=data_base;trusted_connection=Yes;encrypt=No;TrustServerCertificate=Yes;APP=dbt-sqlserver/1.7.4;ConnectRetryCount=1`

When using a the standard sql login flow, it adds the port as expected.

Solved by either adding the port to the `SERVER` line (`0.0.0.0,1444`) + communicating this to users or lifting the windows login piece out of fabric into this adapter.

```yml
dbt_project:
  target: dev
  outputs:
    dev:
      type: sqlserver
      driver: 'ODBC Driver 18 for SQL Server'
      server: 0.0.0.0,1444
      database: data_base
      schema: dbt
      trust_cert: true
      encrypt: false
      windows_login: true
```
