### ISSUE TITLE
Project fails in 1.7.2 using model groups

### ISSUE THREAD

**Issue by hogank3** [dbt-msft/dbt-sqlserver#501]
Dbt project is failing to build after upgrading to 1.7.2. I have models grouped at the project level. For example, here in my dbt_project.yml file.

```yaml
# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
models:
  my_dbt_project:
    # Config indicated by + and applies to all files under models/example/
    EHR:
      +materialized: table
      +schema: EHR
      +group: EHR
```

This throws an error when building the project.
```cmd
23:09:34  Running with dbt=1.7.14
23:09:35  Registered adapter: sqlserver=1.7.4
23:09:35  Unable to do partial parsing because a project config has changed
23:09:38  Encountered an error:
Parsing Error in model Account (models\EHR\Account.sql)
  Invalid group 'EHR', expected one of []
```

It will build if I remove all groups. I also tried grouping at the model level but it produces the same error. I believe it is all valid dbt syntax going off the docs. I did not have any issues with this before upgrading.\
