### ISSUE TITLE
Cannot Authenticate with CLI

### ISSUE THREAD

**Issue by EatZeBaby** [dbt-msft/dbt-sqlserver#82]
I am trying to use the SQL Server adapter with the CLI authentication.
My config is the following : 
```
dbt version: 0.18.1
dbt-mssql version: 0.18.1
python version: 3.7.4
os info: Windows-10-10.0.19041-SP0
```

Here is my profiles.yml
```
my_profile:
  target: dev
  outputs:
    dev:
      type: sqlserver
      driver: 'ODBC Driver 17 for SQL Server'
      server: ip_of_my_server
      port: port_of_my_server
      database: db_of_my_server_that_is_not_master
      schema: my_schema
      authentication: CLI
  ```  
I run `az login` sucessfully 
```❯ az login
You have logged in. Now let us find all the subscriptions to which you have access...
```
But when I run `dbt debug` I encounter the following error : 
```
Connection:
  database: my_db
  schema: my_schema
  port: 1433
  UID: None
  client_id: None
  authentication: CLI
  encrypt: False
  trust_cert: False
  Connection test: ERROR

dbt was unable to connect to the specified database.
The database returned the following error:

  >Database Error
  ('28000', "[28000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Login failed for user '<token-identified principal>'. (18456) (SQLDriverConnect); [28000] [Microsoft][ODBC Driver 17 for SQL 
Server][SQL Server]Login failed for user '<token-identified principal>'. (18456)")
````

If I use : 
``` 
authentication: ActiveDirectoryInteractive
user: me@github.com
```
It works but I have to authenticate at every command executed which is not efficient.
Do you have any idea of what I could be doing wrong ? Or how we can fix this ?
